# Generated by Django 4.2.2 on 2023-06-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lisitng',
            name='name2',
            field=models.CharField(default='SOme String', max_length=350),
        ),
    ]
