# Generated by Django 4.2.2 on 2023-07-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
