# Generated by Django 4.2.2 on 2023-07-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_watchlist_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lisitng',
            new_name='Listing',
        ),
    ]
