# Generated by Django 4.2.2 on 2023-07-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='item_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
